#!/bin/sh
#
# Copyright 2019 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

TEST_DIR=/tmp/backup_restore_test

PD_ADDR="127.0.0.1:2379"
TIDB_IP="127.0.0.1"
TIDB_PORT="4000"
TIDB_ADDR="127.0.0.1:4000"
TIDB_STATUS_ADDR="127.0.0.1:10080"
# actaul tikv_addr are TIKV_ADDR${i}
TIKV_ADDR="127.0.0.1:2016"
TIKV_STATUS_ADDR="127.0.0.1:2018"
TIKV_COUNT=3
TIFLASH_STATUS="127.0.0.1:17000"
TIFLASH_HTTP="127.0.0.1:8125"

install_tiup() {
    if ! which tiup; then
      curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
      export PATH=$PATH:$HOME/.tiup/bin
    fi
}

stop_services() {
    TIUP_TAG=${TEST_NAME-'br-test'}
    killall -9 tiup || true
    killall -9 tikv-server || true
    killall -9 pd-server || true
    killall -9 tidb-server || true
    killall -9 tiflash || true

    for i in $(seq 0 $(($TIKV_COUNT-1))); do
      cp ~/.tiup/data/$TIUP_TAG/tikv-$i/tikv.log $TEST_DIR/tikv$((i+1)).log || true
    done
    cp ~/.tiup/data/$TIUP_TAG/tidb-0/*.log $TEST_DIR/ || true
    cp ~/.tiup/data/$TIUP_TAG/pd-0/*.log $TEST_DIR/ || true
    cp ~/.tiup/data/$TIUP_TAG/tiflash-0/log/*.log $TEST_DIR/ || true
    find "$TEST_DIR" -maxdepth 1 -not -path "$TEST_DIR" -not -name "*.log" | xargs rm -r || true
    cp -r ~/.tiup/data/$TIUP_TAG/prometheus $TEST_DIR/ || true
    rm -rf ~/.tiup/data/$TIUP_TAG
}


start_services() {
    install_tiup
    TIUP_TAG=${TEST_NAME-'br-test'}

    max_retry=3
    for retry_time in $(seq 1 $max_retry); do
        if start_services_impl $@; then
            return 0
        fi
        echo "Failed to start services, but let retry it after $(( $retry_time * 30 )) seconds"
        sleep $(( $retry_time * 30 ))
    done
    echo "Failed to start services after retry $max_retry times."
    return 1
}

tiup_ready() {
    log=${1-tiup.log}

    i=0
    while ! grep "CLUSTER START SUCCESSFULLY" $TEST_DIR/$log; do
        i=$((i+1))
        if [ "$i" -gt 200 ]; then
            echo 'Failed to bootstrap cluster'
            return 1
        fi
        sleep 3
    done
}

start_services_impl() {
    stop_services
    source tests/_utils/make_tiflash_config

    TIDB_CONFIG="${1-tests}/config/tidb.toml"
    TIKV_CONFIG="${1-tests}/config/tikv.toml"
    PD_CONFIG="${1-tests}/config/pd.toml"
    TIFLASH_CONFIG="${1-tests}/config/tiflash.toml"

    if [ ! -e $PD_CONFIG ]; then PD_CONFIG=tests/config/pd.toml; fi
    if [ ! -e $TIFLASH_CONFIG ]; then TIFLASH_CONFIG=tests/config/tiflash.toml; fi

    tiup -T $TIUP_TAG playground --pd.config $PD_CONFIG \
      --kv.config $TIKV_CONFIG \
      --db.config $TIDB_CONFIG \
      --tiflash.config $TIFLASH_CONFIG \
      --kv 3 > $TEST_DIR/tiup.log &

    tiup_ready
}

# TODO when tiup playground supports TLS, use tiup to bootstrap this cluster.
start_services_withTLS() {
    stop_services

    PD_CONFIG="$1/config/pd.toml"
    TIDB_CONFIG="$1/config/tidb.toml"
    TIKV_CONFIG="$1/config/tikv.toml"

    echo $PD_CONFIG
    echo $TIDB_CONFIG
    echo $TIKV_CONFIG

    echo "Starting PD..."
    bin/pd-server \
        --client-urls "https://$PD_ADDR" \
        --log-file "$TEST_DIR/pd.log" \
        --config "$PD_CONFIG" \
        --data-dir "$TEST_DIR/pd" &
    # wait until PD is online...
    i=0
    while ! curl --cacert $1/certificates/ca.pem \
        --cert $1/certificates/client.pem \
        --key $1/certificates/client-key.pem \
        -o /dev/null -sf "https://$PD_ADDR/pd/api/v1/version"; do
        i=$((i+1))
        if [ "$i" -gt 20 ]; then
            echo 'Failed to start PD'
            exit 1
        fi
        sleep 3
    done

    echo "Starting TiKV..."
    for i in $(seq $TIKV_COUNT); do
        bin/tikv-server \
            --pd "$PD_ADDR" \
            -A "$TIKV_ADDR$i" \
            --log-file "$TEST_DIR/tikv${i}.log" \
            -C "$TIKV_CONFIG" \
            -s "$TEST_DIR/tikv${i}" &
    done

    echo "Waiting initializing TiKV..."
    while ! curl --cacert $1/certificates/ca.pem \
            --cert $1/certificates/client.pem \
            --key $1/certificates/client-key.pem \
            -sf "https://$PD_ADDR/pd/api/v1/cluster/status" | grep '"is_initialized": true'; do
       i=$((i+1))
       if [ "$i" -gt 20 ]; then
          echo 'Failed to initialize TiKV cluster'
          exit 1
       fi
       sleep 3
    done

    echo "Starting TiDB..."
    bin/tidb-server \
        -P 4000 \
        --status 10080 \
        --store tikv \
        --config "$TIDB_CONFIG" \
        --path "$PD_ADDR" \
        --log-file "$TEST_DIR/tidb.log" &

    echo "Verifying TiDB is started..."
    i=0
    while ! curl --cacert $1/certificates/ca.pem \
            --cert $1/certificates/client.pem \
            --key $1/certificates/client-key.pem \
            -o /dev/null -sf "https://$TIDB_IP:10080/status"; do
        i=$((i+1))
        if [ "$i" -gt 50 ]; then
            echo 'Failed to start TiDB'
            exit 1
        fi
        sleep 3
    done

    i=0
    while ! curl --cacert $1/certificates/ca.pem \
            --cert $1/certificates/client.pem \
            --key $1/certificates/client-key.pem \
            "https://$PD_ADDR/pd/api/v1/cluster/status" -sf | grep -q "\"is_initialized\": true"; do
        i=$((i+1))
        if [ "$i" -gt 20 ]; then
            echo 'Failed to bootstrap cluster'
            exit 1
        fi
        sleep 3
    done
}
